# Generated by Django 3.0.5 on 2020-06-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userpass',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=500)),
            ],
        ),
    ]
